### ISSUE TITLE
This package is broken pending a move to the new callgraph pkgs 

### ISSUE THREAD

**Issue by 3rf** [3rf/codecoroner#5]
Hopefully I will get some free time to update this before the end of May 2015. If you're feeling squirrelly, you can get it to compile by checking out an old version of the oracle package.

**Comment by ernestoalejo** [comment]
Do you know a specific commit that works correctly with the code?

**Comment by ernestoalejo** [comment]
OK, I figured it out. The last oracle commit you can use that works correctly is: https://github.com/golang/tools/commit/68b5f7541d840b07800dc21d83ebdaa8ca8a771f

**Comment by 3rf** [comment]
Thanks for your interest, Ernesto! This commit removes callgraph support: https://github.com/golang/tools/commit/b28839e4bdc90af193b3e38f473e5f9175158b41

So this one should still work if you use it directly: https://github.com/golang/tools/commit/68b5f7541d840b07800dc21d83ebdaa8ca8a771f

Ultimately this change is going to make things much better--having a real set of packages for callgraphs is much nicer than the hack I was doing! But until we move to the new callgraph packages, things are borked when relying on "go get" :/

**Comment by 3rf** [comment]
Ahh beat me to it by a few seconds, nice :+1:

**Comment by ernestoalejo** [comment]
@3rf At the same time :laughing: haha Thanks. I use this tool from time to time to fix the accumulated issues over time in the code so the temporary checkout it's not so bad in the meantime this gets fixed.

**Comment by 3rf** [comment]
For anyone still tracking this project, I'll be spending a few internal hackathon days next week getting this project back on track. Good things ahead :beers:

**Comment by mblair** [comment]
:trophy:

**Comment by 3rf** [comment]
Moved to the `callgraph/rta` package (https://godoc.org/golang.org/x/tools/go/callgraph/rta) since it seemed best suited for dead code detection. Tests passing and it seems to be working swimmingly on the [mongo-tools](https://github.com/mongodb/mongo-tools) and [evergreen](https://github.com/evergreen-ci/evergreen).

My next task is a complete overhaul of the README, then some other usability enhancements. Please let me know if things are still broken on y'alls end.
