### ISSUE TITLE
Does not compile on Golang 1.5 and 1.6

### ISSUE THREAD

**Issue by vornet** [3rf/codecoroner#9]
go get github.com/3rf/codecoroner
# github.com/3rf/codecoroner/unused
work/src/github.com/3rf/codecoroner/unused/idents.go:56: impossible type switch case: kind (type "go/types".Object) cannot have dynamic type *"golang.org/x/tools/go/types".Func (wrong type for Parent method)
	have Parent() *"golang.org/x/tools/go/types".Scope
	want Parent() *"go/types".Scope
work/src/github.com/3rf/codecoroner/unused/idents.go:79: impossible type switch case: kind (type "go/types".Object) cannot have dynamic type *"golang.org/x/tools/go/types".Func (wrong type for Parent method)
	have Parent() *"golang.org/x/tools/go/types".Scope
	want Parent() *"go/types".Scope

**Comment by 3rf** [comment]
This is fixed in master!
